name: Build the app
on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: lu-explorer
          path: docs
